#!/bin/bash

echo "🚀 DÉPLOIEMENT SÉCURISÉ O2SWITCH - Kreyatik Studio"
echo "=================================================="
echo ""
echo "Ce script est conçu pour éviter les problèmes de cache Blade chez o2switch"
echo ""
echo "EXÉCUTEZ CES COMMANDES SUR VOTRE SERVEUR O2SWITCH:"
echo ""
echo "# 1. Se connecter au serveur"
echo "ssh fite6981@truelle.o2switch.net"
echo ""
echo "# 2. Aller dans le dossier du site"
echo "cd public_html/KreyatikLaravel"
echo ""
echo "# 3. AVANT LE GIT PULL - Sauvegarder le header actuel qui fonctionne"
echo "cp resources/views/components/header.blade.php resources/views/components/header.blade.php.backup"
echo "echo '✅ Backup créé'"
echo ""
echo "# 4. Pull les changements Git"
echo "git pull origin main"
echo ""
echo "# 5. CRITIQUE - Supprimer TOUS les fichiers cache Blade IMMÉDIATEMENT"
echo "rm -f storage/framework/views/*.php"
echo "echo '✅ Cache Blade supprimé'"
echo ""
echo "# 6. Clear TOUS les caches Laravel dans l'ordre"
echo "php artisan view:clear"
echo "php artisan cache:clear"
echo "php artisan config:clear"
echo "php artisan route:clear"
echo "php artisan optimize:clear"
echo "echo '✅ Caches Laravel clear'"
echo ""
echo "# 7. Vérifier que le dossier cache est vide"
echo "ls -la storage/framework/views/"
echo "# Devrait être vide ou contenir seulement .gitignore"
echo ""
echo "# 8. Permissions correctes"
echo "chmod -R 775 storage/framework/views"
echo "chmod -R 775 storage/logs"
echo "echo '✅ Permissions configurées'"
echo ""
echo "# 9. Premier test - Générer le cache"
echo "curl -s https://kreyatikstudio.fr > /dev/null"
echo "echo '✅ Cache généré'"
echo ""
echo "# 10. Vérifier le status HTTP"
echo "curl -I https://kreyatikstudio.fr"
echo "# Devrait retourner: HTTP/2 200"
echo ""
echo "# 11. Vérifier qu'il n'y a pas d'erreurs dans les logs"
echo "tail -30 storage/logs/laravel.log"
echo ""
echo "=================================================="
echo "⚠️  SI VOUS OBTENEZ UNE ERREUR HTTP 500:"
echo ""
echo "# ROLLBACK IMMÉDIAT - Restaurer l'ancien header"
echo "cp resources/views/components/header.blade.php.backup resources/views/components/header.blade.php"
echo "rm -f storage/framework/views/*.php"
echo "php artisan optimize:clear"
echo "curl -I https://kreyatikstudio.fr"
echo "# Le site devrait refonctionner"
echo ""
echo "=================================================="
echo "✅ SI TOUT FONCTIONNE (HTTP 200):"
echo ""
echo "# Tester le structured data"
echo "curl -s https://kreyatikstudio.fr | grep -c 'application/ld+json'"
echo "# Devrait retourner un nombre > 0 (idéalement 2 ou 3)"
echo ""
echo "# Tester avec Google Rich Results"
echo "echo 'Allez sur: https://search.google.com/test/rich-results'"
echo "echo 'Testez: https://kreyatikstudio.fr'"
echo "echo 'Vérifiez que LocalBusiness et WebSite apparaissent'"
echo ""
echo "=================================================="
echo "📋 CHECKLIST POST-DÉPLOIEMENT:"
echo ""
echo "- [ ] HTTP 200 sur curl -I https://kreyatikstudio.fr"
echo "- [ ] Aucune erreur dans storage/logs/laravel.log"
echo "- [ ] Site accessible et navigation fonctionne"
echo "- [ ] Images WebP chargent correctement"
echo "- [ ] Structured data présent (grep application/ld+json)"
echo "- [ ] Google Rich Results Test validé"
echo ""
echo "=================================================="
echo "🎯 POURQUOI CETTE APPROCHE FONCTIONNE CHEZ O2SWITCH:"
echo ""
echo "1. Suppression du cache AVANT que Laravel ne le regénère"
echo "2. Clear de tous les caches dans le bon ordre"
echo "3. Backup automatique pour rollback rapide"
echo "4. Vérifications à chaque étape"
echo "5. Pas de modification manuelle des fichiers"
echo ""
echo "=================================================="
