#!/bin/bash

echo "🚨 FIX URGENT - Cache Blade Corrompu en Production"
echo "=================================================="
echo ""
echo "PROBLÈME: ParseError sur /a-propos"
echo "CAUSE: Cache Blade compilé corrompu chez o2switch"
echo ""
echo "SOLUTION IMMÉDIATE - Exécutez ces commandes:"
echo ""
echo "ssh fite6981@truelle.o2switch.net"
echo "cd public_html/KreyatikLaravel"
echo ""
echo "# 1. SUPPRIMER TOUT LE CACHE BLADE"
echo "rm -f storage/framework/views/*.php"
echo "echo '✅ Cache Blade supprimé'"
echo ""
echo "# 2. SUPPRIMER LE CACHE DE DONNÉES"
echo "rm -rf storage/framework/cache/data/*"
echo "echo '✅ Cache data supprimé'"
echo ""
echo "# 3. CLEAR TOUS LES CACHES LARAVEL"
echo "php artisan view:clear"
echo "php artisan cache:clear"
echo "php artisan config:clear"
echo "php artisan route:clear"
echo "php artisan optimize:clear"
echo "echo '✅ Tous les caches Laravel clear'"
echo ""
echo "# 4. VÉRIFIER LES PERMISSIONS"
echo "chmod -R 775 storage/framework/views"
echo "chmod -R 775 storage/framework/cache"
echo "echo '✅ Permissions OK'"
echo ""
echo "# 5. TESTER LES PAGES"
echo "echo 'Test homepage:'"
echo "curl -I https://kreyatikstudio.fr | head -1"
echo ""
echo "echo 'Test à propos:'"
echo "curl -I https://kreyatikstudio.fr/a-propos | head -1"
echo ""
echo "echo 'Test méthode de travail:'"
echo "curl -I https://kreyatikstudio.fr/methode-travail | head -1"
echo ""
echo "# Tous doivent retourner: HTTP/2 200"
echo ""
echo "=================================================="
echo "⚠️ SI LE PROBLÈME PERSISTE:"
echo ""
echo "# Option 1: Redémarrer PHP-FPM via cPanel"
echo "# Aller sur https://truelle.o2switch.net:2083"
echo "# MultiPHP Manager → Redémarrer PHP-FPM"
echo ""
echo "# Option 2: Vérifier le fichier source sur le serveur"
echo "wc -l resources/views/a-propos/index.blade.php"
echo "grep -c '@push' resources/views/a-propos/index.blade.php"
echo "grep -c '@endpush' resources/views/a-propos/index.blade.php"
echo "# Doit retourner: 1 et 1"
echo ""
echo "# Option 3: Re-pull le code"
echo "git status"
echo "git pull origin main --force"
echo "rm -f storage/framework/views/*.php"
echo "php artisan optimize:clear"
echo ""
